export const ROUTES = {
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  contacts: '/contacts',
  contactNew: '/contacts/new',
  contactEdit: (id: number | string) => `/contacts/${id}/edit`,
  contactGroups: '/contact-groups',
  contactGroupDetail: (id: number | string) => `/contact-groups/${id}`,
  templates: '/templates',
  templateNew: '/templates/new',
  templateEdit: (id: number | string) => `/templates/${id}/edit`,
  campaigns: '/campaigns',
  campaignNew: '/campaigns/new',
  campaignDetail: (id: number | string) => `/campaigns/${id}`,
  campaignEdit: (id: number | string) => `/campaigns/${id}/edit`,
  analytics: '/analytics',
  profile: '/profile',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminActivity: '/admin/activity',
} as const;
