version: "3.9"

services:
  app:
    build: .
    container_name: campaignpro-app

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

    restart: unless-stopped