spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

logging:
  level:
    root: INFO
    com.campaignpro: INFO

